name: Publish Community

on:
  schedule:
    - cron: "00 09 * * *"
  workflow_dispatch:
  push:
    branches:
      - "community/*"

concurrency:
  group: publish-community-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: ${{ matrix.compute_platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compute_platform: ["cu122", "cu121", "cu118", "cpu"]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "formatted_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      - uses: ./.github/workflows/release.yml
        with:
          oneflow_branch: "community"
          compute_platform: ${{ matrix.compute_platform }}
          release_tag: ${{ steps.date.outputs.formatted_date }}
