name: Publish Community

on:
  schedule:
    - cron: "00 09 * * *"
  workflow_dispatch:
  push:
    branches:
      - "community/*"

concurrency:
  group: publish-community-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: ${{ matrix.compute_platform }}
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/release.yml
    strategy:
      fail-fast: false
      matrix:
        compute_platform: ["cu122", "cu121", "cu118", "cpu"]
    with:
      oneflow_branch: "community"
      compute_platform: ${{ matrix.compute_platform }}
