name: Publish Community

on:
  schedule:
    - cron: "00 09 * * *"
  workflow_dispatch:
  push:
    branches:
      - "community/*"

concurrency:
  group: publish-community-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Latest OneFlow
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/release.yml
    with:
      oneflow_branch: "community"
