# This is a basic workflow to help you get started with Actions

name: Publish pip packages to GH releases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      oneflow_branch:
        description: "branch of oneflow"
        type: string
        required: true
      compute_platform:
        description: "compute platform of oneflow"
        type: string
        required: true
      release_tag:
        description: "GH tag for release"
        type: string
        required: true
      oneflow_index:
        description: "index URL of oneflow"
        type: string
        required: false
        default: "https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  extract_urls:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    outputs:
      matrix: ${{ steps.generete_json.outputs.matrix }}
    steps:
      - run: sudo apt-get install jq
      # Runs a single command using the runners shell
      - id: generete_json
        run: |
          matrix=$(curl https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118 | grep -oh 'https.*\.whl' | jq -sR 'split("\n") | map(select(length > 0) | {url: .}) | map({key: (.url | capture("(?<pyv>cp[0-9]+)-cp").pyv), value: .}) | unique_by(.key) | map(.value) | {package: .}')
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [extract_urls]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.extract_urls.outputs.matrix) }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "${{ matrix.package.url }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
