# This is a basic workflow to help you get started with Actions

name: Publish pip packages to GH releases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      oneflow_branch:
        description: "branch of oneflow"
        type: string
        required: true
      oneflow_index:
        description: "index URL of oneflow"
        type: string
        required: false
        default: "https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate_id:
    name: Generate ID of release
    runs-on: ubuntu-latest
    outputs:
      formatted_date: ${{ steps.date.outputs.formatted_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "formatted_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

  # This workflow contains a single job called "build"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [generate_id]
    strategy:
      fail-fast: false
      matrix:
        compute_platform: ["cu122", "cu121", "cu118", "cpu"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl ${{ inputs.oneflow_index}}/${{ inputs.oneflow_branch}}/${{ matrix.compute_platform }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
